### ISSUE TITLE
Top level import Error

### ISSUE THREAD

**Issue by astroclark** [llondon6/nrutils_dev#12]
A basic import of the nrutils module fails to import the internal packages defined in the **init**.py

For example:

``` python
[jclark@taranis] $ python -c "import nrutils"
The highest level init for nrutils is located at: /home/jclark/.local/lib/python2.7/site-packages/nrutils-1.0-py2.7.egg/nrutils/__init__.pyc

>> Initiating nrutils ...

>> Sub-Packages to be imported:
   -> 
   -> 
   -> 
   -> 
>> Please note style conventions:                  
   * lower case function/method/variable names                  
   * no underscore in names unless there are repeated letters, or counfounded syllables                  
   * information is implicitely in time domain unless explicitely stated.                  
   * frequency domain information will start with "fd".

nrutils:

  .: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jclark/.local/lib/python2.7/site-packages/nrutils-1.0-py2.7.egg/nrutils/__init__.py", line 83, in <module>
    exec r'import %s' % p
  File "<string>", line 1
    import 
          ^
SyntaxError: invalid syntax
```

**Comment by llondon6** [comment]
Hi James!

Are you still having this issue? If so, which OS and python version are you using? Are you running in a virtual environment?

**Comment by llondon6** [comment]
I was finally able to reproduce this error. It was caused by bash's find command:

This works on MAC but not lin LINUX
```bash
find ./ -name name -depth 2
```

This works on both
```bash
find ./ -maxdepth 2 -name name
```

You should be able to use nrutils now. Remeber that you will have to do some manual configuration after cloning (for now). This is described in the repo's readme.
